### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by annaprusakova** [AnnaPrusakova/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Hprusakova** [comment]
Whether in success or in failure, I’m proud of every single movie I’ve directed. I’m not really interested in making money. That’s always come as the result of success, but it’s not been my goal, and I’ve had a tough time proving that to people.

**Comment by Hprusakova** [comment]
I'm not the developer yet. But I struggle to learn new technologies and improve my knowledge every day.
