### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by annaprusakova** [AnnaPrusakova/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Hprusakova** [comment]
(818) 695-5000

**Comment by Hprusakova** [comment]
https://www.instagram.com/an_prusakova/
https://www.facebook.com/annaprusakova/
hanna.prusakova@gmail.com
