### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by annaprusakova** [AnnaPrusakova/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Hprusakova** [comment]
**Experience**

September 2020 - till now 
Getting a Master degree in ONAFT

June 2020 
Graduated ONAFT with a red diploma - bachelor degree in Computer Science
- Had a lot of experience with different programming languages and technologies 
- Created a cool Android app "Ragweed"

May 2016
Graduated from the local school 

17th  December 1998 
Born in Odesa, Ukraine
