### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by annaprusakova** [AnnaPrusakova/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Hprusakova** [comment]
**LANGUAGES**
 🇺🇦УКРАЇНСЬКА 🇷🇺РУССКИЙ 🇺🇸 ENGLISH

**SKILLS**
Java Kotlin MySQL PostgreSQL HTML CSS JS JUnit Git REST XML JSON

**CHARACTER**
INDEPENDENT, CURIOUS, COMPETITIVE, DREAMER

**LIKES 😃**
HUMOUR, MOVIES, BOOKS, YOGA, DOGS, OLD MUSIC

**DISLIKES 😞**
PASSIVE-AGGRESSIVE, CLOSED-MINDED PEOPLE, RACISM, CHEMISTRY

**WANTS🙏**
BECOME A DEVELOPER,  TO BE FIT AND HEALTHY, DO NOT BE AFRAID OF MISTAKES

**EDUCATION 🏫**
_Everyday_ 

- Hyperskill, Codewars, HackerRank, YouTube etc.

_Semptember 2020 - December 2021_

- Master degree at ONAFT

_Semptember 2016-June 2020_

- Bachelor degree in Computer Science at ONAFT
